"""changes

Revision ID: 861be0d75de5
Revises: 
Create Date: 2023-07-21 19:40:56.765997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '861be0d75de5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
